openapi: 3.0.0
info:
  title: My API Documentation
  version: 1.0.0
  description: API documentation for Me ))
servers:
  - url: http://localhost:8080/api
    description: Local server
components:
  securitySchemes:
    Bearer:
      type: http
      scheme: bearer
      bearerFormat: JWT
  schemas:
    User:
      type: object
      properties:
        _id:
          type: string
          description: User's unique identifier
        email:
          type: string
          format: email
          description: User's email address
        password:
          type: string
          description: User's hashed password
        name:
          type: string
          description: User name
        surname:
          type: string
          description: User surname
        role:
          type: string
          enum:
            - admin
            - editor
          description: User's role
        tokens:
          type: array
          items:
            type: string
          description: List of user's tokens
        createdAt:
          type: string
          format: date-time
          description: Creation timestamp
        updatedAt:
          type: string
          format: date-time
          description: Update timestamp
        __v:
          type: integer
          description: Version key
    LoginRequest:
      type: object
      required:
        - email
        - password
      properties:
        email:
          type: string
          format: email
          description: User's email address
        password:
          type: string
          description: User's password
    CreateUserRequest:
      type: object
      required:
        - email
        - password
      properties:
        email:
          type: string
          format: email
          description: User's email address
        password:
          type: string
          description: User's password
        name:
          type: string
          description: Enter your name
        surname:
          type: string
          description: Enter your surname
paths:
  /user:
    get:
      tags:
        - User
      summary: Retrieve all users
      responses:
        200:
          description: A list of users
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/User'
        500:
          description: Internal server error
    post:
      tags:
        - User
      summary: Create a new user
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateUserRequest'
      responses:
        201:
          description: User created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
        400:
          description: Bad request, missing or invalid input
        500:
          description: Internal server error
  /user/login:
    post:
      tags:
        - User
      summary: Log in as an existing user
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LoginRequest'
      responses:
        200:
          description: User logged in successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  accessToken:
                    type: string
                    description: Access token for authenticated user
                  refreshToken:
                    type: string
                    description: Refresh token for authenticated user
        400:
          description: Bad request, missing or invalid input
        500:
          description: Internal server error
  /user/tokens:
    put:
      tags:
        - User
      summary: Update tokens for a user
      responses:
        200:
          description: Tokens updated successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  accessToken:
                    type: string
                    description: New access token
        400:
          description: Bad request, missing or invalid input
        500:
          description: Internal server error
  /user/{id}:
    put:
      tags:
        - User
      summary: Update an existing user
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
          description: ID of the user to update
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateUserRequest'
      responses:
        200:
          description: User updated successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
        400:
          description: Bad request, missing or invalid input
        404:
          description: User not found
        500:
          description: Internal server error

    delete:
      tags:
        - User
      summary: Delete an existing user
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
          description: ID of the user to delete
      responses:
        200:
          description: User deleted successfully
        404:
          description: User not found
        500:
          description: Internal server error
